version: '3.8'

services:

  app:
    container_name: hazzweather_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - 80:80
    environment:
      - REACT_APP_API_KEY
      - REACT_APP_URL
      - REACT_APP_ICON_URL
